server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "ahmed"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
  # NO plugins section - we pre-load the JAR named as 1.16.0

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
    oauth:
      enabled: true

logging:
  level:
    root: INFO
    lavalink: INFO
